# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0f\x44igaOlasRequest\x12\r\n\x05nomes\x18\x01 \x03(\t\" \n\rDigaOlasReply\x12\x0f\n\x07message\x18\x01 \x01(\t2c\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12.\n\x08\x44igaOlas\x12\x10.DigaOlasRequest\x1a\x0e.DigaOlasReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=19
  _globals['_HELLOREQUEST']._serialized_end=47
  _globals['_HELLOREPLY']._serialized_start=49
  _globals['_HELLOREPLY']._serialized_end=78
  _globals['_DIGAOLASREQUEST']._serialized_start=80
  _globals['_DIGAOLASREQUEST']._serialized_end=112
  _globals['_DIGAOLASREPLY']._serialized_start=114
  _globals['_DIGAOLASREPLY']._serialized_end=146
  _globals['_GREETER']._serialized_start=148
  _globals['_GREETER']._serialized_end=247
# @@protoc_insertion_point(module_scope)
